# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    webhook:
        routing:
            line:
                service: App\Webhook\SampleParser
            line/callback:
                service: App\Webhook\LoginParser
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
